### ISSUE TITLE
Suggestion: Use the PlantUML web API

### ISSUE THREAD

**Issue by nomssi** [larshp/ABAP-Object-Visualizer#6]
Hello Lars,

I suggest to use the PlantUML online server http://www.plantuml.com/plantuml/uml/
to display the data., i.e. 

    @startdot
    digraph G {
      "Welcome" -> "To"
      "To" -> "Web"
      "To" -> "GraphViz via PlantUML!"
    }
    @enddot

will work.
The benefit would be to automate the display task without local installation of GraphViz. You can find my ABAP interface to the PlantUML API in class `lcl_plant_uml` implemented [here](https://github.com/nomssi/ABAP-to-PlantUML/tree/master/class%20diagram/latest).

best regards,
JNN

**Comment by nomssi** [comment]
I have implemented the suggestion in my fork: it works.

**Comment by larshp** [comment]
pull requests are welcome
